name: piquet_list_web
description: A simple Flutter web app to generate piquet shift schedules.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
